site_name: 'Ievms-ruby'
pages:
- [index.md, Home]
- [cli.md, ievmsrb (CLI)]
- [library.md, Ievms-ruby library]
- [provisioning_examples.md, Provisioning Examples]
theme: readthedocs
#theme: cerulean
#theme: amelia
#theme: bootstrap
#theme: cosmo
#theme: cyborg
#theme: flatly
#theme: journal
#theme: mkdocs
#theme: readable
#theme: simplex
#theme: slate
#theme: spacelab
#theme: united
#theme: yeti
